version: "3"


services:
  
  AK24:
    container_name: sqli-filtered
    image: sqli-f
    build: .
    ports:
      - 8011:80
    restart: always

    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_DATABASE=sqli
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  db:
    image: mysql
    hostname: sqli
    environment:
      - MYSQL_DATABASE=sqli
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 6445:80
