version: "3"


services:
  
  AK24:
    container_name: sql-injection
    image: sqli
    build: .
    ports:
      - 8010:80
    restart: always

    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_DATABASE=sqli
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  db:
    image: mysql
    hostname: sqli
    environment:
      - MYSQL_DATABASE=sqli
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 6441:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
